version: "3.9"

networks:
  movie-collection-network:

services:
  movie-collection:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-collection-container
    ports:
      - "8080:80"
    depends_on:
      - movie-collection-db
    environment:
      - ConnectionStrings__Default=Host=movie-collection-db;Port=5432;Database=movie_collection_db;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:80
    networks:
      - movie-collection-network

  movie-collection-db:
    image: postgres:latest
    container_name: movie-collection-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movie_collection_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - movie-collection-data:/var/lib/postgresql/data
    networks:
      - movie-collection-network

volumes:
  movie-collection-data:
